# Generated by Django 2.2 on 2019-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.RenameField(
            model_name='careers',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
