# Generated by Django 2.2 on 2019-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20190519_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='other_docs',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='upload_cv',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
