# Generated by Django 2.2 on 2019-05-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20190520_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='other_docs',
        ),
    ]
