# Generated by Django 2.2 on 2019-04-09 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('martial_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=10)),
                ('Date_of_birth', models.DateField()),
                ('Place_of_birth', models.CharField(max_length=100)),
                ('Contact_Address', models.TextField()),
                ('Phone_No_2', models.PositiveIntegerField()),
                ('Academic_qualification', models.CharField(choices=[('PHD', 'PHD'), ('MSC', 'MSC'), ('BSC', 'BSC'), ('SSCE', 'SSCE'), ('JSCE', 'JSCE')], max_length=10)),
                ('Next_of_kin', models.CharField(max_length=50)),
                ('Phone_No', models.PositiveIntegerField(help_text='Enter Phone Number of Next of Kin')),
                ('Session', models.CharField(choices=[('Morning (10 am)', 'Morning (10 am)'), ('Afternoon (12pm - 1pm)', 'Afternoon (12pm - 1pm)')], max_length=20)),
                ('Disablities', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2019, 4, 9, 13, 45, 2, 489090))),
            ],
        ),
    ]
