# Generated by Django 2.2 on 2019-04-09 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 13, 46, 16, 105339, tzinfo=utc)),
        ),
    ]
