# Generated by Django 2.2 on 2019-04-09 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Profile', '0002_auto_20190409_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 13, 51, 20, 586787, tzinfo=utc)),
        ),
    ]
