# Generated by Django 2.2 on 2019-04-09 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Profile', '0003_auto_20190409_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
