# Generated by Django 2.2 on 2019-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190407_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
