# Generated by Django 2.2 on 2019-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20190407_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='tutor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
