# Generated by Django 2.2 on 2019-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20190407_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
