# Generated by Django 2.2 on 2019-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
