# Generated by Django 2.2 on 2019-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_register_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
