# Generated by Django 2.2 on 2019-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20190408_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
